title: MarcelCon
description: > # this means to ignore newlines until "baseurl:"
  The Event of a Decade
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://marcelcon.com" # the base hostname & protocol for your site

date: <del>July 3 - 5, 2020</del> Postponed!
location: Boston, MA 

# formspree: https://formspree.io/hello.world@gmail.com

# Build settings
markdown: kramdown

facebook:
  app_id: 

logo: "../css/2016_style/img/icon-large.png"

social: 
  name: Your Facebook Page
  link: "https://www.facebook.com/"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2017_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: facebook
  #   url: https://www.facebook.com
  # - title: twitter
  #   url: https://twitter.com

# Build settings
markdown: kramdown
permalink: pretty